#define BG_COLOR 						15
#define BG_BUTTON_DEFAULT 				7
#define BG_BUTTON_SELECT 				4
#define TEXT_BUTTON_SELECT 				15
#define TEXT_BUTTON_DEFAULT				0
#define BORDER_COLOR 					0
#define TIPS 							12
#define TEXT_COLOR 						0
#define TEXT_COLOR_SELECTED 			2
#define LINE							7
#define PANEL							4

#define MAXLIST_DAUSACH 				200
#define MAX_DOC_GIA 					8191
#define QUEUE_CAPACITY 					8191

const int ENTER = 13;
const int BACKSPACE = 8;
const int SPACE = 32;

enum Window {DANH_SACH_DAU_SACH,THEM_DAU_SACH, HIEU_CHINH_DAU_SACH, DANH_MUC_SACH, DANH_SACH_DOC_GIA, THEM_DOC_GIA, HIEU_CHINH_DOC_GIA, XOA_DOC_GIA, MUON_SACH, TRA_SACH, TOP_TEN};
enum SubWindow {NHAP_SACH, THEM_SACH, HIEU_CHINH_SACH, XAC_NHAN_TRA_SACH, XAC_NHAN_LAM_MAT_SACH, TRANG_NULL ,CONFIRM_POPUP, CONFIRM_POPUP_NONE};
enum ScanType{ ONLY_NUMBER, ONLY_TEXT, TEXT_NUMBER, SPACE_TEXT, DELETE_SPACE_UPPERCASE, LIMIT_CHARACTER, SPACE_TEXT_UPPERCASE, SPACE_TEXT_NUM_UPPERCASE, TEXT_NUM_ADD_COMMA_UPPERCASE, TIM_DAU_SACH, TIM_MA_SACH, DATE_ONLY};
enum errorOpenfile{DAU_SACH, SACH, DOC_GIA, MUON_TRA, DSDS_FULL};
enum ModeDocGia{MODE_MA_THE, MODE_TEN, MODE_QUA_HAN};
